services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=8000 
      - DATABASE_URL=postgresql://user:password@db:5432/library_db
      - JWT_SECRET=b2648dee98fafcc6445d52862888d561758d82cf22760902e35e26f1630dcebe
      - NODE_ENV=129e78010e12d2a589b1100b668b6429a3a5bfc1bd9e7dd78027243e9697df7e
      

  db:
    image: postgres:18-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: